- name: Install | Make sure postgresql-common is installed
  apt:
    name: postgresql-common
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"

- name: Install | Ensure cluster automatic creation is disabled
  lineinfile:
    path: /etc/postgresql-common/createcluster.conf
    regexp: '^\s*(#\s*)?create_main_cluster\s*='
    line: "create_main_cluster = false"

- name: Install | Install PostgreSQL
  apt:
    name:
      - "postgresql-{{ postgresql_version }}"
      - "postgresql-client-{{ postgresql_version }}"
      - "postgresql-contrib-{{ postgresql_version }}"
      - "libpq-dev"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"

#- name: Install | PGTune
#  apt:
#    name: pgtune
#    state: present
#    update_cache: yes
#    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
#  environment: "{{ postgresql_env }}"
#  when: postgresql_pgtune

- name: Install | Extensions | Make sure the postgis extensions are installed
  apt:
    name:
      - "postgresql-{{ postgresql_version }}-postgis-{{ postgresql_ext_postgis_version }}"
      - "postgresql-{{ postgresql_version }}-postgis-{{ postgresql_ext_postgis_version }}-scripts"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"
  when: postgresql_ext_install_postgis
  notify:
    - Restart postgresql
