# file: postgresql/tasks/users.yml

- name: Users | Ensure PostgreSQL is running
  systemd:
    name: "{{ postgresql_service_name }}"
    state: started
  become: yes

- name: Users | Make sure the PostgreSQL users are present
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.pass | default(omit) }}"
    encrypted: "{{ item.encrypted | default(omit) }}"
    role_attr_flags: "{{ item.role_attr_flags | default(omit) }}"
    state: present
    login_user: "{{ postgresql_cluster_user }}"
  become: yes
  become_user: "{{ postgresql_cluster_user }}"
  loop: "{{ postgresql_users }}"
  no_log: yes
  when: postgresql_users|length > 0
