- name: Ensure redis is installed
  apt: name=redis-server state=present
- name: Ensure redis is configured
  copy:
    src: etc/redis/redis.conf
    dest: /etc/redis/redis.conf
  notify:
    - Restart redis
- name: Ensure redis is started and enabled
  service:
    name: redis
    enabled: true
    state: started
