- name: Add latest nginx PPA
  apt_repository:
    repo: 'ppa:nginx/stable'
  when: nginx_latest_ppa|bool

- name: Ensure Nginx is installed
  apt:
    name:
      - nginx
      - nginx-extras
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"

- name: Ensure dhparams are present
  copy:
    dest: /etc/nginx/dhparams.pem
    src: dhparams.pem

- name: Install nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - reload nginx

# See https://bugs.mageia.org/show_bug.cgi?id=26397 and https://github.com/Perl/perl5/issues/17154
- name: Disable perl module on Focal
  file:
    path: /etc/nginx/modules-enabled/50-mod-http-perl.conf
    state: absent
  notify:
    - reload nginx
  when: ansible_distribution_release == "focal"

- name: Copy helpful util conf includes
  template:
    src: "{{ item }}.j2"
    dest: /etc/nginx/{{ item }}
  loop:
    - uwsgi_params
    - proxy_params
    - fastcgi_params
  notify:
    - reload nginx

- name: Ensure includes dir is present
  file:
    path: /etc/nginx/includes
    state: directory

- name: Install letsencrypt includes
  copy:
    src: letsencrypt.conf
    dest: /etc/nginx/includes/letsencrypt.conf
  register: letsencrypt_includes

- name: Ensure default site is not enabled
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Ensure basic configuration for letsencrypt is present
  copy:
    src: 99-letsencrypt.conf
    dest: /etc/nginx/sites-available/99-letsencrypt.conf
  register: letsencrypt_conf

- name: Ensure basic configuration for letsencrypt is enabled
  file:
    path: /etc/nginx/sites-enabled/99-letsencrypt.conf
    src: ../sites-available/99-letsencrypt.conf
    state: link

# nginx must be reloaded now in case an ACME challenge is made in the same playbook
# to get a certificate
- name: Reload nginx for letsencrypt
  service: name=nginx state=reloaded
  when: letsencrypt_includes.changed or letsencrypt_conf.changed
  tags:
    - skip_ansible_lint

- name: Copy additional nginx.service configuration
  copy:
    src: nginx.service.d
    dest: /etc/systemd/system/
  notify:
    - reload systemd
    - restart nginx

- name: Ensure nginx is started and enabled
  service: name=nginx enabled=yes state=started

- name: Ensure goaccess is available
  apt:
    name: goaccess
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"

- name: Ensure goaccess config file is present
  copy:
    src: goaccess.conf
    dest: /etc/goaccess.conf

- name: Ensure /var/www is owned by www-data
  file:
    path: /var/www
    owner: www-data
    group: www-data
    recurse: yes

- name: Open port 80
  ufw:
    rule: allow
    port: "80"
  when: not cloudflare_protected|bool

- name: Open port 443
  ufw:
    rule: allow
    port: "443"
  when: not cloudflare_protected|bool

- import_tasks: cloudflare.yml
  when: cloudflare_protected|bool
