---
namespace: "aktiur"
name: "basic_roles"
version: "0.2.6"
readme: "README.md"
authors:
  - "Maud Royer"
  - "Salomé Cheysson"
repository: "https://github.com/aktiur/basic_roles"
license:
  - "GPL-3.0-only"
tags:
  - collection
  - basic
  - web
