galaxy_info:
  role_name: uv
  description: Installe UV
  author: Salomé Cheysson
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
        - resolute
  license: GPL-3.0-only
  min_ansible_version: 2.6
