---
- name: Add repo for python
  ansible.builtin.apt_repository:
    repo: 'ppa:deadsnakes/ppa'
  register: python_repo
  when: python_use_ppa|bool

- name: Ensure python is installed
  ansible.builtin.apt:
    name:
      - "python{{ python_version }}"
      - "python{{ python_version }}-dev"
      - "python{{ python_version }}-venv"
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"
