---
- name: Install MariaDB
  ansible.builtin.apt:
    name:
      - mariadb-server
      - mariadb-client
      - python{{ system_python_version }}-mysqldb
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time | default(3600) }}"
