galaxy_info:
  role_name: nextcloud
  description: Un rôle qui installe Nextcloud en snap
  author: Maud Royer & Salomé Cheysson
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
        - resolute
  license: GPL-3.0-only
  min_ansible_version: "2.6"
