---

- name: Reload systemd
  ansible.builtin.systemd:
    daemon-reload: true

- name: Restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
