- name: reload systemd
  systemd:
    daemon-reload: yes

- name: restart journald
  service: name=systemd-journald state=restarted

- name: apply netplan
  ansible.builtin.command:
    cmd: netplan apply
