---
- name: Create app group
  ansible.builtin.group:
    name: "{{ django_group }}"
    system: true

- name: Create app user
  ansible.builtin.user:
    name: "{{ django_user }}"
    group: "{{ django_group }}"
    system: true

- name: Ensure app directory exists
  ansible.builtin.file:
    path: "{{ django_directory }}"
    state: directory
    owner: "{{ django_user }}"
    group: "{{ django_group }}"
    mode: "0755"

- name: Ensure static directory exists
  ansible.builtin.file:
    path: "{{ django_static_directory }}"
    state: directory
    mode: "0755"

- name: Ensure media directory exists
  ansible.builtin.file:
    path: "{{ django_media_directory }}"
    state: directory
    mode: "0755"
    owner: "{{ django_user }}"
    group: "{{ django_group }}"

- name: Ensure shell utility script is present
  ansible.builtin.template:
    src: django-shell.j2
    dest: "/usr/local/bin/{{ django_app_name }}-shell"
    mode: "0755"

- name: Ensure manage utility is present
  ansible.builtin.template:
    src: manage.j2
    dest: "/usr/local/bin/{{ django_app_name }}-manage"
    mode: "0755"

- name: Set up the virtualenv
  ansible.builtin.import_role:
    name: virtualenv
  tags: deploy

- name: Set up uwsgi and its configuration
  ansible.builtin.import_tasks: uwsgi.yml
  when: django_uwsgi_services|length > 0

- name: Set up celery
  ansible.builtin.import_tasks: celery.yml
  when: django_celery_services|length > 0

- name: Set up nginx configuration for django
  ansible.builtin.import_tasks: nginx.yml
  when: django_nginx_conf|bool
