- name: Install django application
  ansible.builtin.import_tasks: install.yml
  tags:
    - provision

- name: Set up the environment
  ansible.builtin.import_tasks: environment.yml
  tags:
    - deploy

- name: Run deployment scripts for django
  ansible.builtin.import_tasks: django.yml
  tags:
    - deploy
