---
galaxy_info:
  role_name: node
  description: Installe node js
  author: Jill Royer
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
        - jammy
  license: GPL-3.0-only
  min_ansible_version: "2.6"
