---
- name: Add nodesource signing key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add Node.js {{ node_major_version }}.x repositories
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ node_major_version }}.x \
    {{ ansible_distribution_release }} main"
    filename: nodesource

- name: Ensure Node.js is installed
  apt:
    name: nodejs
    state: latest
    update_cache: true

- name: Get latest version of npm
  command: npm install npm@latest -g
