---
- name: Check we are on Ubuntu release
  ansible.builtin.fail:
    msg: You need to use Ubuntu Server
  when: ansible_distribution != "Ubuntu"

- name: Check we are on correct release
  ansible.builtin.fail:
    msg: You need to use one of the supported releases
  when: ansible_distribution_release not in supported_releases

- name: Ensure hostname is correctly set
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Ensure sudoers file is present
  ansible.builtin.copy:
    src: sudoers
    dest: /etc/sudoers
    owner: root
    group: root
    mode: "0440"

- name: Upgrade apt packages
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time | default(3600) }}"

- name: Ensure essentials packages are installed
  ansible.builtin.apt:
    name:
      - build-essential
      - python{{ system_python_version }}-pip
      - software-properties-common
      - apt-transport-https
      - apt-utils
      - debconf-utils
      - git
      - unzip
      - net-tools
      - ufw
      - sudo
      - rsyslog
      - fail2ban

# to add label to a volume : 'e2label /dev/sda5 "MY_BACKUP"'
- name: Ensure additional filesystems are mounted
  ansible.posix.mount:
    state: mounted
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    fstype: "{{ item.fstype | default('ext4') }}"
  loop: "{{ mounts }}"

- name: Ensure required locales are installed
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  with_items: "{{ locales }}"

- name: Ensure default locale is set
  ansible.builtin.lineinfile:
    path: /etc/default/locale
    regexp: "^LANG="
    line: "LANG={{ default_locale }}"
  when: default_locale is defined

- name: Ensure system wide known hosts file exists
  ansible.builtin.copy:
    src: ssh_known_hosts
    dest: /etc/ssh/ssh_known_hosts
    owner: root
    group: root
    mode: "0644"

- name: Ensure journal directory is created so that logs are persisted
  ansible.builtin.file:
    path: /var/log/journal
    state: directory
    group: systemd-journal
    mode: "02755"
  notify:
    - restart journald


# Dans sa séquence d'initialisation, UFW fait un truc un peu bête : il règle la
# politique par défaut *avant* d'avoir inséré la règle qui autorise les paquets
# appartenant à des connexions déjà ouvertes.
#
# Résultat, si on met la politique par défaut à DENY, le changement de politique
# se met à bloquer la connexion des disques réseaux, ce qui coupe les connexions
# déjà existantes… et notamment celles aux disques réseau, ce qui fait planter le
# boot.
#
# Du coup, comme workaround, on indique comme politique par défaut ALLOW, mais
# on rajoute à la chaîne qu'UFW utilise comme post-traitement pour les paquets
# entrants une règle qui droppe tout, dans un fichier que UFW charge *après*
# avoir créé la règle qui autorise les paquets des connexions ouvertes.
#
# On retrouve donc bien le comportement souhaité, avec l'inconvénient majeur que
# rien de tout cela n'est directement visible dans l'interface de UFW qui
# affiche simplement que la politique par défaut est ALLOW.

- name: ufw default allow not to block nbd
  ufw:
    policy: allow

- name: ufw allow ssh
  ufw:
    rule: allow
    port: "22"

- name: ufw drop all packets in "after rules"
  lineinfile:
    path: /etc/ufw/after{{ item }}.rules
    line: "-A ufw{{ item }}-reject-input -j DROP"
    insertbefore: COMMIT
  with_items:
    - ''
    - '6'

- name: enable ufw
  ufw:
    state: enabled

- name: ensure diagnostic tools are installed
  apt:
    name:
      - mtr
      - knot-dnsutils
      - nmap
      - iftop
      - htop
      - vnstat
      - hping3
      - nload
