---
- name: Make sure apt packages for mstmp are present
  ansible.builtin.apt:
    name:
      - msmtp
      - msmtp-mta

- name: Set up configuration file
  ansible.builtin.template:
    src: msmtprc.j2
    dest: /etc/msmtprc
    mode: "0644"
