galaxy_info:
  role_name: postgresql
  description: Installe et configure un serveur postgresql
  author: Arthur Cheysson
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - eoan
  license: GPL-3.0-only
  min_ansible_version: 2.6
